In [14]:
import numpy as np

In [27]:
A = np.array([[2, 4, 6], [1, 2, 3], [3, 6, 9]]) # 3x3
B = np.array([[1, 2, 1], [2, 4, 2]]) # 2x3
# should be able to do B x A, but not A x B

In [28]:
B

array([[1, 2, 1],
       [2, 4, 2]])

In [29]:
res = [[0 for x in range(3)] for y in range(3)]
 
# explicit for loops
for i in range(len(B)):
    for j in range(len(A[0])):
        for k in range(len(A)):
 
            # resulted matrix
            res[i][j] += B[i][k] * A[k][j]
 
print(res)

[[7, 14, 21], [14, 28, 42], [0, 0, 0]]


In [30]:
np.dot(B, A)

array([[ 7, 14, 21],
       [14, 28, 42]])

In [31]:
B * A

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [35]:
C = np.array([[2, 2, 2, 2]])

In [36]:
B * C

ValueError: operands could not be broadcast together with shapes (2,3) (1,4) 

In [34]:
A * C

array([[ 4,  8, 12],
       [ 2,  4,  6],
       [ 6, 12, 18]])